### ISSUE TITLE
WHAT

### ISSUE THREAD

**Issue by ghost** [heestand-xyz/Tabs#1]
# EXCUSE ME?

![IMG_0021](https://github.com/heestand-xyz/Tabs/assets/100056951/328c871c-9999-4aa1-9ed1-53fe58aaf992)
![IMG_0020](https://github.com/heestand-xyz/Tabs/assets/100056951/6b9b74ef-d471-4095-9666-93c9b5290d27)

**Comment by ghost** [comment]
Yes I `import`ed `Tabs` and `SwiftUI`

**Comment by aehlke** [comment]
figure it out? looks like you put the body var INSIDE your init constructor.

**Comment by ghost** [comment]
> figure it out? looks like you put the body var INSIDE your init constructor.

Oh… didn’t see that. I’ll try!

**Comment by aehlke** [comment]
separate the 'var body' to be OUTSIDE the init constructor
